/*
 * Created on 16 d�c. 2013 ( Time 15:14:48 )
 * Generated by Telosys Tools Generator ( version 2.0.7 )
 */

package org.demo.couchbase.utils;

public class DBConstants {

	public final static String CONFIGURATION_FILE_NAME = "couchbase.properties";
    
	public final static String COUCHBASE_URI = "couchbase.uris";
	public final static String COUCHBASE_BUCKET = "couchbase.bucket";
	public final static String COUCHBASE_PASSWORD = "couchbase.password";
	
	public final static String DATABASE_VERSION = "couchbase.database.version";
	public final static String DATABASE_VERSION_DOC_ID = "DB_VERSION";
        
	public final static String DESIGN_NAME_DOMAIN = "domain";
	public final static String DESIGN_NAME_ALL = "all_domain";

}